module.exports = {
  defaultIgnores: false,
  parserPreset: {
    parserOpts: {
      headerPattern: /^([^()!:\s]+)(?:\(([^()!\r\n]+)\))?(!)?: (.*)$/,
      headerCorrespondence: ["type", "scope", "breaking", "subject"],
      noteKeywords: ["BREAKING CHANGE", "BREAKING-CHANGE"],
    },
  },
  rules: {
    "body-leading-blank": [2, "always"],
    "body-max-line-length": [2, "always", 72],
    "footer-leading-blank": [2, "always"],
    "footer-max-line-length": [2, "always", 72],
    "header-max-length": [2, "always", 50],
    "header-trim": [2, "always"],
    "scope-case": [2, "always", "lower-case"],
    "scope-empty": [2, "never"],
    "scope-enum": [
      2,
      "always",
      [
        "agents",
        "audit",
        "changelog",
        "ci",
        "community",
        "commit",
        "config",
        "docs",
        "git",
        "hooks",
        "readme",
        "release",
        "security",
        "support",
        "templates",
        "tools",
        "validation",
      ],
    ],
    "scope-max-length": [2, "always", 13],
    "subject-case": [
      2,
      "never",
      ["sentence-case", "start-case", "pascal-case", "upper-case"],
    ],
    "subject-empty": [2, "never"],
    "subject-full-stop": [2, "never", "."],
    "type-case": [2, "always", "lower-case"],
    "type-empty": [2, "never"],
    "type-enum": [
      2,
      "always",
      [
        "build",
        "chore",
        "ci",
        "docs",
        "feat",
        "fix",
        "perf",
        "refactor",
        "revert",
        "style",
        "test",
      ],
    ],
  },
};
